version: "3.9"
services:
  zoo_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    links:
      - pg_db
    volumes:
      - .:/app
  pg_db:
    image: postgres
    ports:
      - "${DB_LOCAL_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
