version: "3.9"
services:
  zoo_app:
    build: .
    ports:
      - "4000:4000"
    links:
      - pg_db
  pg_db:
    image: postgres
    ports:
      - "5679:5432"
    environment:
      POSTGRES_PASSWORD: gdk1JlTM
      POSTGRES_DB: zoo
